---
ad_os_family_name: debian

ad_required_packages:
  - realmd
  - sssd
  - sssd-tools
  - libnss-sss
  - libpam-sss
  - adcli
  - samba-common-bin
  - krb5-user
  - packagekit
  - oddjob
  - oddjob-mkhomedir

ad_mkhomedir_method: pam_auth_update

ad_sssd_service_name: sssd
ad_oddjobd_service_name: oddjobd
